# Generated by Django 3.2.7 on 2021-09-13 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان سفارش')),
                ('total_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ کل')),
                ('status', models.CharField(choices=[('wait', 'در انتظار پرداخت'), ('Paid', 'پرداخت شده'), ('cancel', 'لغو شده')], default='wait', max_length=6)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shopping', to='customers.customer', verbose_name='مشتری')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('shopping', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='orders.shopping')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order', to='products.product', verbose_name='محصول')),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.shopping', verbose_name='سفارش مربوطه')),
            ],
        ),
    ]
